version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: atm_sphere_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: atm_db
      MYSQL_USER: atm_user
      MYSQL_PASSWORD: atm_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: